### PR TITLE
Added the --devel flag so that it also support for the development versions

### PR DESCRIPTION
**Pull request by shivam-Purohit**
As the new keptn development version is here, we needed to support the development version as well. 
If there are some conflicts , do let me know I will make changes.

### CODE REVIEW

**Comment by vadasambar** [comment]
@shivam-Purohit you need to sign off your commit. 
```
git commit --amend --signoff
got push --force-with-lease
```

**Comment by shivam-Purohit** [comment]
Hope that solves the issue. @vadasambar do let me know if any more changes are required.

**Comment by vadasambar** [comment]
Not sure who maintains this repo. @keptn-sandbox/maintainers can we get a review on this :pray: 
More context in https://github.com/keptn-sandbox/action-install-keptn/issues/6

**Comment by vadasambar** [comment]
Also mentioning @TannerGabriel and @mowies since I see them active in the repo.

**Review by mowies — APPROVED** [review]

**Comment by mowies** [comment]
Approved, but we need somebody else to approve who has write permissions. Maybe @Raffy23 ?

**Review by Raffy23 — APPROVED** [review]
LGTM

**Pull request merged**
